### ISSUE TITLE
Does not work on heroku

### ISSUE THREAD

**Issue by dkrusenstrahle** [pusher/pusher-http-ruby#52]
Hello,

I have setup Pusher gem successfully in my Rails 3.2.14 app on my local machine. All works fine. But when I upload and run it on Heroku I get this:

from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `block in require'
2013-11-01T16:25:04.271869+00:00 app[web.1]: /app/app/models/signature.rb:1:in`<top (required)>': Signature is not a class (TypeError)
2013-11-01T16:25:04.272002+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/engine.rb:444:in `block (2 levels) in eager_load!'
2013-11-01T16:25:04.272008+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/engine.rb:443:in`each'
2013-11-01T16:25:04.271931+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
2013-11-01T16:25:04.272145+00:00 app[web.1]:    from /app/config/environment.rb:5:in`<top (required)>'

I am using a init file called pusher.rb with this content:

Pusher.app_id = 'XXX'
Pusher.key = 'XXXXXXX'
Pusher.secret = 'XXXXXXX'

What can be wrong here?

**Comment by xn** [comment]
I forked the Signature gem and renamed it Xignature. I also forked the signature gem and updated the dependencies to point to xignature. Specs are green. https://github.com/xn/pusher-http-ruby
