### ISSUE TITLE
Unknown auth_key

### ISSUE THREAD

**Issue by varun-raj** [pusher/pusher-http-ruby#96]
With basic setup in rails app I tried pusher. When I try this in rails console `rails c` I got this error
```
2.2.1 :053 > Pusher.trigger('my_channel', 'my_event', {message: 'hello world'})
Pusher::Error: Bad request: Unknown auth_key
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/pusher-0.14.5/lib/pusher/request.rb:88:in `handle_response'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/pusher-0.14.5/lib/pusher/request.rb:38:in `send_sync'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/pusher-0.14.5/lib/pusher/resource.rb:18:in `post'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/pusher-0.14.5/lib/pusher/client.rb:144:in `post'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/pusher-0.14.5/lib/pusher/client.rb:228:in `trigger'
	from (irb):53
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/varun/Projects/Allt/bin/rails:9:in `<top (required)>'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/varun/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/varun/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/varun/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

```

**Comment by zimbatm** [comment]
Did you set the `Pusher.key` and `Pusher.secret` or `Pusher.url` ?

**Comment by varun-raj** [comment]
I solved it. It's the issue with `host`

**Comment by zimbatm** [comment]
Okay, great !
